-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
    - id: yapf
      name: "yapf"

      
-   repo: https://github.com/pycqa/flake8
    rev: '5.0.4'  # pick a git hash / tag to point to
    hooks:
    - id: flake8 
      # args duplicated from setup.cfg as pre-commit flake8 is buggy using --config=setup.cfg
      # perhaps .flake8 works? 
      args: 
        - "--ignore=D100, D101, D102, D103, D104, D202, D212, W503, N803, N806"
        - "--max-line-length=120"
        - "--docstring-convention=google"
        - "--exclude=detectree2/data_loading/*,detectree2/models/train_tune.py"
        - "--max-complexity=10"
        # - "--config=setup.cfg"

      additional_dependencies: [flake8-docstrings]

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: isort (python)
 
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
    - id: mypy
      entry: mypy detectree2/
      args: ['--config=setup.cfg']
      language_version: python3.9
      pass_filenames: false
